version: '3'

services:
  nginx:
    # build: ./nginx
    image: docker.io/soybackend/lumenconcept-provider-nginx:v2
    depends_on:
     - django
    ports:
      - "8001:80"
    networks:
      - webnet

  django:
    # build: ./app
    command: /usr/local/bin/gunicorn lumenconcept_provider.wsgi:application -w 2 -b :8000
    env_file: .env
    image: docker.io/soybackend/lumenconcept-provider-service:v2
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
    networks:
      - webnet
networks:
  webnet:
